### ISSUE TITLE
[fix] It's difficult to edit workbook in real-time because any new rows without lat/long coordinates break the entire map

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/savmaps#2]
At the event, the map kept breaking inexplicably. The reason is that users were entering new data but hadn't yet geocoded it yet.

### Workaround temporarily
Instead of editing the main workbook itself, make your own copy and edit it, making sure that **every** single row/entry has valid lat/long columns. Then copy the entirety directly back into main workbook. This is akin somewhat to GitHub's forking process.

**Comment by roblingle** [comment]
👆 that's weird, I don't remember assigning myself. 🤔 

Might be happening here: https://github.com/opensavannah/savmaps/blob/d738385ee43cbcef043c34a9a3fb901d846a396c/scripts/map.js#L127

Which is here in the source repo: https://github.com/JackDougherty/leaflet-maps-with-google-sheets/blob/090919f27e899cdf54ec98214adc419ab4248722/scripts/map.js#L127

@carlvlewis I see there's a video how-to... any chance you could give us the steps to run this locally, hopefully in dev mode so that it's not minified.

Could be as simple as this:
`if (point && point.Latitude !== '' && point.Longitude !== '') {`

**Comment by royemosby** [comment]
@roblingle I'll be talking to @carlvlewis about running this locally tomorrow afternoon. On initial glance, it appears that the repo is missing several directories ( `/csv/ ` and `/geometry/` ) and their respective contents. I don't know yet if this is something that leaflet or tabletop makes...

**Comment by roblingle** [comment]
That's great. Anything we can do to lower the bar for others to join will help.

From what I've seen so far: 
- check out the code
- open index.html

That's about it. You can add a `debugger` line or otherwise breakpoints anywhere in map.js, then reload the page with a console open. 

@carlvlewis when I check out the code and run it locally, it doesn't run like it does at SavMaps.io. 

If I hit the pause button in the sources tab of Chrome devtools, I can see that it's stuck in a loop that checks this line: https://github.com/opensavannah/savmaps/blob/master/scripts/map.js#L692

`completePolylines` and `compeltePolygons` are always false. I think that's because the polyline and polygon tabs have bogus data URLs and the map script just keeps trying them. If I change that line to just `if (completePoints)` then it loads the map very quickly. 

**Even with missing coordinates, I think**

**Comment by carlvlewis** [comment]
This has been fixed and am closing issue, but the workaround prevents demographic layers from being added.

**Comment by roblingle** [comment]
What was the fix and workaround? 

This looks like my comment above, was that all we needed? https://github.com/opensavannah/savmaps/commit/e21779401c72ef2e218e8f82c29533151da72957

**Comment by roblingle** [comment]
Let's try to make better commit messages. ;)

What changed and why, related issue # in the title or comment. If we ever need to go back and figure out why something was done that makes it way easier.

**Comment by roblingle** [comment]
Fwiw, an alternative solution might have been leaving the code and removing the bogus data from the polyline and polygon tabs.

**Comment by carlvlewis** [comment]
It wasn't bogus geospatial data. Data was valid.

Yes, basically determined it was the same line you mentioned in 'maps.js' and disabled the polygon and polyline functions altogether.
